// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Relay.Data;

#nullable disable

namespace Relay.Migrations
{
    [DbContext(typeof(RelayDbContext))]
    [Migration("20230515092811_NullContent")]
    partial class NullContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Relay.Data.Balance", b =>
                {
                    b.Property<string>("PublicKey")
                        .HasColumnType("text");

                    b.Property<long>("CurrentBalance")
                        .HasColumnType("bigint");

                    b.HasKey("PublicKey");

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("Relay.Data.BalanceTopup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BalanceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BalanceId");

                    b.ToTable("BalanceTopups");
                });

            modelBuilder.Entity("Relay.Data.BalanceTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("BalanceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BalanceTopupId")
                        .HasColumnType("text");

                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Value")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BalanceId");

                    b.HasIndex("BalanceTopupId");

                    b.HasIndex("EventId");

                    b.ToTable("BalanceTransactions");
                });

            modelBuilder.Entity("Relay.RelayNostrEvent", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "content");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasAnnotation("Relational:JsonPropertyName", "created_at");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasAnnotation("Relational:JsonPropertyName", "kind");

                    b.Property<string>("PublicKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "pubkey");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasAnnotation("Relational:JsonPropertyName", "sig");

                    b.HasKey("Id");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("Relay.RelayNostrEventTag", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<List<string>>("Data")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TagIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventTags");

                    b.HasAnnotation("Relational:JsonPropertyName", "tags");
                });

            modelBuilder.Entity("Relay.Data.BalanceTopup", b =>
                {
                    b.HasOne("Relay.Data.Balance", "Balance")
                        .WithMany()
                        .HasForeignKey("BalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Balance");
                });

            modelBuilder.Entity("Relay.Data.BalanceTransaction", b =>
                {
                    b.HasOne("Relay.Data.Balance", "Balance")
                        .WithMany("BalanceTransactions")
                        .HasForeignKey("BalanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relay.Data.BalanceTopup", "Topup")
                        .WithMany("BalanceTransactions")
                        .HasForeignKey("BalanceTopupId");

                    b.HasOne("Relay.RelayNostrEvent", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.Navigation("Balance");

                    b.Navigation("Event");

                    b.Navigation("Topup");
                });

            modelBuilder.Entity("Relay.RelayNostrEventTag", b =>
                {
                    b.HasOne("Relay.RelayNostrEvent", "Event")
                        .WithMany("Tags")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Relay.Data.Balance", b =>
                {
                    b.Navigation("BalanceTransactions");
                });

            modelBuilder.Entity("Relay.Data.BalanceTopup", b =>
                {
                    b.Navigation("BalanceTransactions");
                });

            modelBuilder.Entity("Relay.RelayNostrEvent", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
